version: 2.1

jobs:
  build:
    working_directory: ~/metecho
    docker:
      - image: oddbirds/pyjs:v0.4.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - metecho-py-{{ checksum "requirements/prod.txt" }}-{{ checksum
              "requirements/dev.txt" }}
            - metecho-py-
      - restore_cache:
          keys:
            - metecho-npm-{{ checksum "yarn.lock" }}
            - metecho-npm-
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/prod.txt
            pip install -r requirements/dev.txt
      - run:
          name: Compile Front-End Assets
          command: yarn prod
      - persist_to_workspace:
          root: .
          paths:
            - ./dist
            - ./venv
            - ./node_modules
      - save_cache:
          key:
            metecho-py-{{ checksum "requirements/prod.txt" }}-{{ checksum
            "requirements/dev.txt" }}
          paths:
            - ./venv
      - save_cache:
          key: metecho-npm-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  lint:
    working_directory: ~/metecho
    docker:
      - image: oddbirds/pyjs:v0.4.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: |
            . venv/bin/activate
            yarn lint:nofix

  test-client:
    working_directory: ~/metecho
    docker:
      - image: oddbirds/pyjs:v0.4.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test JS
          command: yarn test:js:coverage
      - store_artifacts:
          path: coverage
          destination: js-reports
      - store_test_results:
          path: coverage
      - persist_to_workspace:
          root: .
          paths:
            - coverage

  test-python:
    working_directory: ~/metecho
    docker:
      - image: oddbirds/pyjs:v0.4.0
        environment:
          DATABASE_URL: postgres://ubuntu:circle_test@localhost:5432/circle_test
          DB_ENCRYPTION_KEY: MMkDMBfYL0Xoz3Xu1ENs3AkdCZdJoks5PNlUBkK7KDc=
          DJANGO_DEBUG: False
          DJANGO_HASHID_SALT: test_hash_id
          DJANGO_SECRET_KEY: test_secret_key
          DJANGO_SETTINGS_MODULE: config.settings.test
          SECURE_SSL_REDIRECT: False
          SFDX_CLIENT_CALLBACK_URL: circle_test
          SFDX_CLIENT_ID: circle_test
          SFDX_CLIENT_SECRET: circle_test
          SFDX_HUB_KEY: circle_test
      - image: circleci/redis:6.0
      - image: circleci/postgres:12.5
        environment:
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: circle_test
          POSTGRES_USER: ubuntu
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run Database Migrations
          command: |
            . venv/bin/activate
            python manage.py migrate --no-input
      - run:
          name: Test Python
          command: |
            . venv/bin/activate
            pytest --junitxml=pycov/pytest-junit.xml
      - store_artifacts:
          path: htmlcov
          destination: py-reports
      - store_test_results:
          path: pycov
      - persist_to_workspace:
          root: .
          paths:
            - .coverage

  report-test-coverage:
    working_directory: ~/metecho
    docker:
      - image: oddbirds/pyjs:v0.4.0
    environment:
      COVERALLS_PARALLEL: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Report Test Coverage
          command: |
            if [ -n "${COVERALLS_REPO_TOKEN}" ]; then
              . venv/bin/activate
              yarn test:js:report-coverage
              yarn test:py:report-coverage
              curl -k "https://coveralls.io/webhook?repo_token=${COVERALLS_REPO_TOKEN}" -d "payload[build_num]=${CIRCLE_BUILD_NUM}&payload[status]=done"
            fi
      - run:
          name: Check Test Coverage
          command: |
            . venv/bin/activate
            yarn test:js:check-coverage
            yarn test:py:check-coverage

  build-docs:
    working_directory: ~/metecho
    docker:
      - image: oddbirds/pyjs:v0.4.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build Documentation
          command: |
            . venv/bin/activate
            cd docs
            make html

  deploy-storybook:
    working_directory: ~/metecho
    docker:
      - image: oddbirds/pyjs:v0.4.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - 'd6:e7:86:ee:3d:de:12:95:d9:59:63:90:55:4f:da:79'
      - run:
          name: Deploy Storybook
          command: |
            if [ -n "${DEPLOY_STORYBOOK}" ]; then
              yarn deploy-storybook --ci
            fi

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test-client:
          requires:
            - build
      - test-python:
          requires:
            - build
      - build-docs:
          requires:
            - build
      - deploy-storybook:
          requires:
            - build
          filters:
            branches:
              only: main
      - report-test-coverage:
          requires:
            - test-client
            - test-python
