name: Test
on:
  push:
  pull_request:
    types: [reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup-docker-compose
        with:
          # Only this step sets the cache for future runs
          cache-to: type=gha,mode=max
      - name: Lint
        run: docker-compose run --no-deps web yarn lint:nofix

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup-docker-compose
      - name: Test frontend
        run: docker-compose run --no-deps web yarn test:js:coverage
      - name: Upload coverage reports
        run:
          docker-compose run -e COVERALLS_REPO_TOKEN --no-deps web yarn
          test:js:report-coverage
      - name: Check coverage
        run: docker-compose run --no-deps web yarn test:js:check-coverage

  backend:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: setup
        uses: ./.github/setup-docker-compose
      - name: Test backend
        run: >
          docker-compose run -e DJANGO_DEBUG=false -e SECURE_SSL_REDIRECT=false
          -e SFDX_CLIENT_SECRET="sample secret" -e
          SFDX_CLIENT_CALLBACK_URL="sample callback" -e SFDX_CLIENT_ID="sample
          id" -e SFDX_HUB_KEY="sample key" -e
          DB_ENCRYPTION_KEY=MMkDMBfYL0Xoz3Xu1ENs3AkdCZdJoks5PNlUBkK7KDc= web
          yarn test:py
      - name: Upload coverage reports
        run:
          docker-compose run -e COVERALLS_REPO_TOKEN --no-deps web yarn
          test:py:report-coverage
      - name: Check coverage
        run: docker-compose run --no-deps web yarn test:py:check-coverage
